// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SlackFunction
 */
export interface SlackFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/notifications/slack.
 */
export class SlackFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SlackFunctionProps) {
    super(scope, id, {
      description: 'src/notifications/slack.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/notifications/slack.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}